//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyM_CRUD.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class DataBase : global::System.Configuration.ApplicationSettingsBase {
        
        private static DataBase defaultInstance = ((DataBase)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DataBase())));
        
        public static DataBase Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("52.161.107.170")]
        public string ServidorPgSql {
            get {
                return ((string)(this["ServidorPgSql"]));
            }
            set {
                this["ServidorPgSql"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mym")]
        public string BaseDatosPgSql {
            get {
                return ((string)(this["BaseDatosPgSql"]));
            }
            set {
                this["BaseDatosPgSql"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("postgres")]
        public string UsuarioPgSql {
            get {
                return ((string)(this["UsuarioPgSql"]));
            }
            set {
                this["UsuarioPgSql"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PassPgSql {
            get {
                return ((string)(this["PassPgSql"]));
            }
            set {
                this["PassPgSql"] = value;
            }
        }
    }
}
